language: minimal

sudo: false

dist: xenial

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

env:
  - WHICH=externalproject
  # JSON package does not play well with FetchContent
  #- WHICH=fetchcontent

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gfortran
    update: true
  homebrew:
    packages:
      - gcc
      - cmake
      - pipenv
    update: true

matrix:
  fast_finish: true

before_install:
  - ./.scripts/travis/install.sh

install:
  - pipenv install --three
  - pipenv run python --version

before_script:
  - test -n $FC && unset FC && export FC=gfortran;
  - cmake --version

script:
  - export PATH=$HOME/Deps/cmake/$CMAKE_VERSION/bin${PATH:+:$PATH}
  - cd "$WHICH"
  - cmake -H. -Bbuild
  - cmake --build build -- VERBOSE=1
  # Testing
