language: minimal

sudo: false

dist: xenial

cache:
  timeout: 1000
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.6
      addons:
        apt:
          packages:
            - cmake
            - gfortran
    - os: osx
      python: 3.6

install:
  - ./.scripts/travis/install.sh
  - pipenv install --three
  - pipenv run python --version

before_script:
  - test -n $FC && unset FC && export FC=gfortran;

script:
  - cmake -H. -Bbuild
  - cmake --build build -- VERBOSE=1
  # Testing
